DELIMITER //
CREATE PROCEDURE repete_consulta16____ (limite TINYINT UNSIGNED)
BEGIN
    DECLARE contador TINYINT UNSIGNED DEFAULT 0;
    loop_teste: LOOP
        SET contador = contador + 1;
        
        IF contador >= limite THEN
            leave loop_teste;
        END IF;
SELECT
	P_BRAND,
	P_TYPE,
	P_SIZE,
	COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM
	PARTSUPP,
	PART
WHERE
	P_PARTKEY = PS_PARTKEY
	AND P_BRAND <> 'BRAND#34'
	AND P_TYPE NOT LIKE 'LARGE BRUSHED%'
	AND P_SIZE IN (48, 19, 12, 4, 41, 7, 21, 39)
	AND PS_SUPPKEY NOT IN (
		SELECT
			S_SUPPKEY
		FROM
			SUPPLIER
		WHERE
			S_COMMENT LIKE '%CUSTOMER%COMPLAINTS%'
	)
GROUP BY
	P_BRAND,
	P_TYPE,
	P_SIZE
ORDER BY
	SUPPLIER_CNT DESC,
	P_BRAND,
	P_TYPE,
	P_SIZE;







    END loop loop_teste;
END//
DELIMITER ;

-- Testando:
CALL repete_consulta16____(31);
